development:
  username: bhammond
  api_key: 850842e4a357f1a0f8bdc312c32922d7
  container: dixie_direct_images
test:
  username: bhammond
  api_key: 850842e4a357f1a0f8bdc312c32922d7
  container: dixie_direct_images
production:
  username: bhammond
  api_key: 850842e4a357f1a0f8bdc312c32922d7
  container: dixie_direct_images